apiVersion: apps/v1
kind: Deployment
metadata:
  name: app24-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app24
  template:
    metadata:
      labels:
        app: app24
    spec:
      containers:
      - name: app24-container
        image: nginx:latest
        ports:
        - containerPort: 80
