apiVersion: apps/v1
kind: Deployment
metadata:
  name: app13-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app13
  template:
    metadata:
      labels:
        app: app13
    spec:
      containers:
      - name: app13-container
        image: nginx:latest
        ports:
        - containerPort: 80
