apiVersion: apps/v1
kind: Deployment
metadata:
  name: app30-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app30
  template:
    metadata:
      labels:
        app: app30
    spec:
      containers:
      - name: app30-container
        image: nginx:latest
        ports:
        - containerPort: 80
