apiVersion: apps/v1
kind: Deployment
metadata:
  name: app15-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app15
  template:
    metadata:
      labels:
        app: app15
    spec:
      containers:
      - name: app15-container
        image: nginx:latest
        ports:
        - containerPort: 80
