apiVersion: apps/v1
kind: Deployment
metadata:
  name: app39-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app39
  template:
    metadata:
      labels:
        app: app39
    spec:
      containers:
      - name: app39-container
        image: nginx:latest
        ports:
        - containerPort: 80
