apiVersion: apps/v1
kind: Deployment
metadata:
  name: app28-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app28
  template:
    metadata:
      labels:
        app: app28
    spec:
      containers:
      - name: app28-container
        image: nginx:latest
        ports:
        - containerPort: 80
