apiVersion: apps/v1
kind: Deployment
metadata:
  name: app11-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app11
  template:
    metadata:
      labels:
        app: app11
    spec:
      containers:
      - name: app11-container
        image: nginx:latest
        ports:
        - containerPort: 80
