apiVersion: apps/v1
kind: Deployment
metadata:
  name: app37-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app37
  template:
    metadata:
      labels:
        app: app37
    spec:
      containers:
      - name: app37-container
        image: nginx:latest
        ports:
        - containerPort: 80
