apiVersion: apps/v1
kind: Deployment
metadata:
  name: app22-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app22
  template:
    metadata:
      labels:
        app: app22
    spec:
      containers:
      - name: app22-container
        image: nginx:latest
        ports:
        - containerPort: 80
