apiVersion: apps/v1
kind: Deployment
metadata:
  name: app19-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app19
  template:
    metadata:
      labels:
        app: app19
    spec:
      containers:
      - name: app19-container
        image: nginx:latest
        ports:
        - containerPort: 80
