apiVersion: apps/v1
kind: Deployment
metadata:
  name: app31-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app31
  template:
    metadata:
      labels:
        app: app31
    spec:
      containers:
      - name: app31-container
        image: nginx:latest
        ports:
        - containerPort: 80
