apiVersion: apps/v1
kind: Deployment
metadata:
  name: app38-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app38
  template:
    metadata:
      labels:
        app: app38
    spec:
      containers:
      - name: app38-container
        image: nginx:latest
        ports:
        - containerPort: 80
