apiVersion: apps/v1
kind: Deployment
metadata:
  name: app23-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app23
  template:
    metadata:
      labels:
        app: app23
    spec:
      containers:
      - name: app23-container
        image: nginx:latest
        ports:
        - containerPort: 80
