apiVersion: apps/v1
kind: Deployment
metadata:
  name: app7-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app7
  template:
    metadata:
      labels:
        app: app7
    spec:
      containers:
      - name: app7-container
        image: nginx:latest
        ports:
        - containerPort: 80
