apiVersion: apps/v1
kind: Deployment
metadata:
  name: app14-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app14
  template:
    metadata:
      labels:
        app: app14
    spec:
      containers:
      - name: app14-container
        image: nginx:latest
        ports:
        - containerPort: 80
