apiVersion: apps/v1
kind: Deployment
metadata:
  name: app4-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app4
  template:
    metadata:
      labels:
        app: app4
    spec:
      containers:
      - name: app4-container
        image: nginx:latest
        ports:
        - containerPort: 80
