apiVersion: apps/v1
kind: Deployment
metadata:
  name: app20-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app20
  template:
    metadata:
      labels:
        app: app20
    spec:
      containers:
      - name: app20-container
        image: nginx:latest
        ports:
        - containerPort: 80
