apiVersion: apps/v1
kind: Deployment
metadata:
  name: app8-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app8
  template:
    metadata:
      labels:
        app: app8
    spec:
      containers:
      - name: app8-container
        image: nginx:latest
        ports:
        - containerPort: 80
