apiVersion: apps/v1
kind: Deployment
metadata:
  name: app33-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app33
  template:
    metadata:
      labels:
        app: app33
    spec:
      containers:
      - name: app33-container
        image: nginx:latest
        ports:
        - containerPort: 80
