apiVersion: apps/v1
kind: Deployment
metadata:
  name: app27-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app27
  template:
    metadata:
      labels:
        app: app27
    spec:
      containers:
      - name: app27-container
        image: nginx:latest
        ports:
        - containerPort: 80
