apiVersion: apps/v1
kind: Deployment
metadata:
  name: app18-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app18
  template:
    metadata:
      labels:
        app: app18
    spec:
      containers:
      - name: app18-container
        image: nginx:latest
        ports:
        - containerPort: 80
